#defaultowy plik, może być zbudowany z docker-compose up
#buduje backend z kontenerów i stawia frontend w trybie 'hot reload' (zmiany w plikach źródłowych są automatycznie przenoszone)
#na frontend

services:
  api:
    image: ghcr.io/mathapppw/api:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=HTTP://0.0.0.0:5000
    networks:
      - frontend_network

  frontend:
    build:
      context: ../Frontend 
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    volumes:
      - ../Frontend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=http://api:5000
    networks:
      - frontend_network
    depends_on:
      - api

networks:
  frontend_network:

