#do testowania API nie buduje frontendu
services:
  api:
    image: ghcr.io/mathapppw/api:latest
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:5000
      - ASPNETCORE_ENVIRONMENT=Production
    networks:
      - backend_network

networks:
  backend_network:
